export const testData = {
    lat: 51.5074,
    lon: -0.1278,
    timezone: 'Europe/London',
    timezone_offset: 3600,
    current: {
        dt: 1695041908,
        sunrise: 1695015572,
        sunset: 1695060616,
        temp: 18.7,
        feels_like: 18.79,
        pressure: 998,
        humidity: 83,
        dew_point: 15.76,
        uvi: 2.23,
        clouds: 75,
        visibility: 10000,
        wind_speed: 5.66,
        wind_deg: 250,
        weather: [
            {
                id: 803,
                main: 'Clouds',
                description: 'broken clouds',
                icon: '04d',
            },
        ],
    },
    hourly: [
        {
            dt: 1695038400,
            temp: 18.41,
            feels_like: 18.5,
            pressure: 998,
            humidity: 84,
            dew_point: 15.66,
            uvi: 2.5,
            clouds: 74,
            visibility: 10000,
            wind_speed: 5.3,
            wind_deg: 208,
            wind_gust: 10.06,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            pop: 0.84,
            rain: {
                '1h': 0.31,
            },
        },
        {
            dt: 1695042000,
            temp: 18.7,
            feels_like: 18.79,
            pressure: 998,
            humidity: 83,
            dew_point: 15.76,
            uvi: 2.23,
            clouds: 75,
            visibility: 8733,
            wind_speed: 5.38,
            wind_deg: 238,
            wind_gust: 10.54,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            pop: 0.76,
        },
        {
            dt: 1695045600,
            temp: 18.74,
            feels_like: 18.78,
            pressure: 999,
            humidity: 81,
            dew_point: 15.41,
            uvi: 1.73,
            clouds: 77,
            visibility: 10000,
            wind_speed: 7.17,
            wind_deg: 274,
            wind_gust: 12.2,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            pop: 0.8,
        },
        {
            dt: 1695049200,
            temp: 18.48,
            feels_like: 18.39,
            pressure: 1000,
            humidity: 77,
            dew_point: 14.38,
            uvi: 1.09,
            clouds: 73,
            visibility: 10000,
            wind_speed: 6.21,
            wind_deg: 267,
            wind_gust: 12.82,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            pop: 0.8,
        },
        {
            dt: 1695052800,
            temp: 18.35,
            feels_like: 18.12,
            pressure: 1001,
            humidity: 72,
            dew_point: 13.22,
            uvi: 0.68,
            clouds: 62,
            visibility: 10000,
            wind_speed: 6.75,
            wind_deg: 266,
            wind_gust: 11.59,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            pop: 0.8,
        },
        {
            dt: 1695056400,
            temp: 16.74,
            feels_like: 16.35,
            pressure: 1003,
            humidity: 72,
            dew_point: 11.67,
            uvi: 0.22,
            clouds: 49,
            visibility: 10000,
            wind_speed: 6.39,
            wind_deg: 279,
            wind_gust: 11.5,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            pop: 0.78,
        },
        {
            dt: 1695060000,
            temp: 15.35,
            feels_like: 14.66,
            pressure: 1005,
            humidity: 66,
            dew_point: 9.02,
            uvi: 0,
            clouds: 36,
            visibility: 10000,
            wind_speed: 5.86,
            wind_deg: 266,
            wind_gust: 11.01,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            pop: 0.78,
        },
        {
            dt: 1695063600,
            temp: 14.78,
            feels_like: 13.93,
            pressure: 1007,
            humidity: 62,
            dew_point: 7.46,
            uvi: 0,
            clouds: 0,
            visibility: 10000,
            wind_speed: 5.47,
            wind_deg: 259,
            wind_gust: 11.09,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695067200,
            temp: 14.34,
            feels_like: 13.45,
            pressure: 1007,
            humidity: 62,
            dew_point: 7.17,
            uvi: 0,
            clouds: 7,
            visibility: 10000,
            wind_speed: 5.27,
            wind_deg: 252,
            wind_gust: 11.83,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695070800,
            temp: 14.29,
            feels_like: 13.47,
            pressure: 1008,
            humidity: 65,
            dew_point: 7.78,
            uvi: 0,
            clouds: 38,
            visibility: 10000,
            wind_speed: 5.73,
            wind_deg: 248,
            wind_gust: 12.08,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695074400,
            temp: 14.11,
            feels_like: 13.35,
            pressure: 1008,
            humidity: 68,
            dew_point: 8.19,
            uvi: 0,
            clouds: 54,
            visibility: 10000,
            wind_speed: 5.8,
            wind_deg: 243,
            wind_gust: 11.82,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695078000,
            temp: 13.91,
            feels_like: 13.18,
            pressure: 1009,
            humidity: 70,
            dew_point: 8.53,
            uvi: 0,
            clouds: 63,
            visibility: 10000,
            wind_speed: 5.57,
            wind_deg: 239,
            wind_gust: 11.71,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695081600,
            temp: 13.61,
            feels_like: 12.91,
            pressure: 1009,
            humidity: 72,
            dew_point: 8.64,
            uvi: 0,
            clouds: 69,
            visibility: 10000,
            wind_speed: 5.38,
            wind_deg: 238,
            wind_gust: 11.42,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695085200,
            temp: 13.38,
            feels_like: 12.68,
            pressure: 1009,
            humidity: 73,
            dew_point: 8.65,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5.21,
            wind_deg: 241,
            wind_gust: 11.03,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695088800,
            temp: 13.29,
            feels_like: 12.58,
            pressure: 1009,
            humidity: 73,
            dew_point: 8.53,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5.1,
            wind_deg: 233,
            wind_gust: 10.75,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695092400,
            temp: 13.22,
            feels_like: 12.53,
            pressure: 1009,
            humidity: 74,
            dew_point: 8.58,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5.08,
            wind_deg: 232,
            wind_gust: 11.13,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695096000,
            temp: 13.19,
            feels_like: 12.5,
            pressure: 1009,
            humidity: 74,
            dew_point: 8.69,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5,
            wind_deg: 230,
            wind_gust: 11.1,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695099600,
            temp: 13.29,
            feels_like: 12.66,
            pressure: 1009,
            humidity: 76,
            dew_point: 9.02,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5.15,
            wind_deg: 226,
            wind_gust: 12.17,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695103200,
            temp: 13.79,
            feels_like: 13.21,
            pressure: 1009,
            humidity: 76,
            dew_point: 9.66,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5.29,
            wind_deg: 222,
            wind_gust: 12.67,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695106800,
            temp: 15,
            feels_like: 14.54,
            pressure: 1008,
            humidity: 76,
            dew_point: 10.65,
            uvi: 0.14,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.22,
            wind_deg: 218,
            wind_gust: 13.69,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695110400,
            temp: 16.28,
            feels_like: 15.9,
            pressure: 1008,
            humidity: 74,
            dew_point: 11.5,
            uvi: 0.45,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.21,
            wind_deg: 217,
            wind_gust: 14.96,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695114000,
            temp: 17.41,
            feels_like: 17.06,
            pressure: 1007,
            humidity: 71,
            dew_point: 12.12,
            uvi: 0.94,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.75,
            wind_deg: 219,
            wind_gust: 15.81,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695117600,
            temp: 17.68,
            feels_like: 17.36,
            pressure: 1007,
            humidity: 71,
            dew_point: 12.35,
            uvi: 0.84,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.48,
            wind_deg: 222,
            wind_gust: 15.97,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.04,
        },
        {
            dt: 1695121200,
            temp: 17.81,
            feels_like: 17.47,
            pressure: 1007,
            humidity: 70,
            dew_point: 12.32,
            uvi: 1.1,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.64,
            wind_deg: 224,
            wind_gust: 15.35,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.04,
        },
        {
            dt: 1695124800,
            temp: 17.28,
            feels_like: 16.97,
            pressure: 1007,
            humidity: 73,
            dew_point: 12.44,
            uvi: 1.2,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.65,
            wind_deg: 224,
            wind_gust: 15.16,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.08,
        },
        {
            dt: 1695128400,
            temp: 17.08,
            feels_like: 16.85,
            pressure: 1007,
            humidity: 77,
            dew_point: 13.04,
            uvi: 0.51,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.45,
            wind_deg: 223,
            wind_gust: 14.97,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.19,
        },
        {
            dt: 1695132000,
            temp: 16.96,
            feels_like: 16.85,
            pressure: 1007,
            humidity: 82,
            dew_point: 13.87,
            uvi: 0.4,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.5,
            wind_deg: 225,
            wind_gust: 15.29,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            pop: 0.39,
            rain: {
                '1h': 0.18,
            },
        },
        {
            dt: 1695135600,
            temp: 16.93,
            feels_like: 16.9,
            pressure: 1006,
            humidity: 85,
            dew_point: 14.32,
            uvi: 0.24,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.23,
            wind_deg: 226,
            wind_gust: 15.04,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            pop: 0.76,
            rain: {
                '1h': 0.32,
            },
        },
        {
            dt: 1695139200,
            temp: 17.1,
            feels_like: 17.09,
            pressure: 1006,
            humidity: 85,
            dew_point: 14.46,
            uvi: 0.45,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.17,
            wind_deg: 227,
            wind_gust: 14.7,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            pop: 0.86,
            rain: {
                '1h': 0.28,
            },
        },
        {
            dt: 1695142800,
            temp: 17.55,
            feels_like: 17.53,
            pressure: 1006,
            humidity: 83,
            dew_point: 14.47,
            uvi: 0.14,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.25,
            wind_deg: 227,
            wind_gust: 14.37,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.84,
        },
        {
            dt: 1695146400,
            temp: 17.52,
            feels_like: 17.44,
            pressure: 1006,
            humidity: 81,
            dew_point: 14.27,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.32,
            wind_deg: 228,
            wind_gust: 14.7,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.74,
        },
        {
            dt: 1695150000,
            temp: 17.47,
            feels_like: 17.44,
            pressure: 1006,
            humidity: 83,
            dew_point: 14.47,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.8,
            wind_deg: 222,
            wind_gust: 14.27,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695153600,
            temp: 17.37,
            feels_like: 17.33,
            pressure: 1006,
            humidity: 83,
            dew_point: 14.46,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.05,
            wind_deg: 218,
            wind_gust: 14.69,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695157200,
            temp: 17.55,
            feels_like: 17.5,
            pressure: 1006,
            humidity: 82,
            dew_point: 14.35,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.13,
            wind_deg: 220,
            wind_gust: 14.86,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695160800,
            temp: 17.48,
            feels_like: 17.4,
            pressure: 1006,
            humidity: 81,
            dew_point: 14.21,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.08,
            wind_deg: 220,
            wind_gust: 14.51,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695164400,
            temp: 17.5,
            feels_like: 17.42,
            pressure: 1006,
            humidity: 81,
            dew_point: 14.12,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.93,
            wind_deg: 217,
            wind_gust: 14.51,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695168000,
            temp: 17.38,
            feels_like: 17.29,
            pressure: 1005,
            humidity: 81,
            dew_point: 14.09,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.95,
            wind_deg: 216,
            wind_gust: 14.65,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695171600,
            temp: 17.47,
            feels_like: 17.39,
            pressure: 1005,
            humidity: 81,
            dew_point: 14.04,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.96,
            wind_deg: 216,
            wind_gust: 14.52,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695175200,
            temp: 17.51,
            feels_like: 17.43,
            pressure: 1004,
            humidity: 81,
            dew_point: 14.08,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.79,
            wind_deg: 213,
            wind_gust: 14.16,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695178800,
            temp: 17.5,
            feels_like: 17.42,
            pressure: 1003,
            humidity: 81,
            dew_point: 14.1,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.71,
            wind_deg: 211,
            wind_gust: 13.99,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695182400,
            temp: 17.51,
            feels_like: 17.41,
            pressure: 1003,
            humidity: 80,
            dew_point: 14.1,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.91,
            wind_deg: 212,
            wind_gust: 14.39,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695186000,
            temp: 17.49,
            feels_like: 17.38,
            pressure: 1002,
            humidity: 80,
            dew_point: 13.93,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.99,
            wind_deg: 207,
            wind_gust: 14.7,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695189600,
            temp: 17.48,
            feels_like: 17.37,
            pressure: 1002,
            humidity: 80,
            dew_point: 13.88,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.97,
            wind_deg: 208,
            wind_gust: 14.95,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1695193200,
            temp: 17.69,
            feels_like: 17.55,
            pressure: 1002,
            humidity: 78,
            dew_point: 13.79,
            uvi: 0.09,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.2,
            wind_deg: 206,
            wind_gust: 15.14,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            pop: 0.32,
            rain: {
                '1h': 0.12,
            },
        },
        {
            dt: 1695196800,
            temp: 18.12,
            feels_like: 18,
            pressure: 1001,
            humidity: 77,
            dew_point: 14.02,
            uvi: 0.31,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.6,
            wind_deg: 207,
            wind_gust: 15.3,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.32,
        },
        {
            dt: 1695200400,
            temp: 18.59,
            feels_like: 18.41,
            pressure: 1001,
            humidity: 73,
            dew_point: 13.63,
            uvi: 0.66,
            clouds: 100,
            visibility: 10000,
            wind_speed: 7.65,
            wind_deg: 207,
            wind_gust: 14.9,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            pop: 0.34,
            rain: {
                '1h': 0.16,
            },
        },
        {
            dt: 1695204000,
            temp: 19.55,
            feels_like: 19.39,
            pressure: 1000,
            humidity: 70,
            dew_point: 13.86,
            uvi: 0.65,
            clouds: 99,
            visibility: 10000,
            wind_speed: 7.91,
            wind_deg: 203,
            wind_gust: 14.85,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.32,
        },
        {
            dt: 1695207600,
            temp: 20.24,
            feels_like: 20.07,
            pressure: 1000,
            humidity: 67,
            dew_point: 13.92,
            uvi: 0.85,
            clouds: 99,
            visibility: 10000,
            wind_speed: 8.44,
            wind_deg: 201,
            wind_gust: 14.96,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.48,
        },
    ],
    daily: [
        {
            dt: 1695034800,
            sunrise: 1695015572,
            sunset: 1695060616,
            moonrise: 1695028740,
            moonset: 1695064140,
            moon_phase: 0.11,
            temp: {
                day: 18.81,
                min: 14.11,
                max: 19.14,
                night: 14.11,
                eve: 16.74,
                morn: 16.36,
            },
            feels_like: {
                day: 18.84,
                night: 13.35,
                eve: 16.35,
                morn: 16.45,
            },
            pressure: 999,
            humidity: 80,
            dew_point: 15.29,
            wind_speed: 7.17,
            wind_deg: 274,
            wind_gust: 12.82,
            weather: [
                {
                    id: 501,
                    main: 'Rain',
                    description: 'moderate rain',
                    icon: '10d',
                },
            ],
            clouds: 69,
            pop: 1,
            rain: 4.85,
            uvi: 2.5,
        },
        {
            dt: 1695121200,
            sunrise: 1695102067,
            sunset: 1695146877,
            moonrise: 1695119760,
            moonset: 1695151500,
            moon_phase: 0.14,
            temp: {
                day: 17.81,
                min: 13.19,
                max: 17.81,
                night: 17.48,
                eve: 17.55,
                morn: 13.29,
            },
            feels_like: {
                day: 17.47,
                night: 17.4,
                eve: 17.53,
                morn: 12.66,
            },
            pressure: 1007,
            humidity: 70,
            dew_point: 12.32,
            wind_speed: 7.75,
            wind_deg: 219,
            wind_gust: 15.97,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            clouds: 100,
            pop: 0.86,
            rain: 0.78,
            uvi: 1.2,
        },
        {
            dt: 1695207600,
            sunrise: 1695188562,
            sunset: 1695233137,
            moonrise: 1695210960,
            moonset: 1695239220,
            moon_phase: 0.17,
            temp: {
                day: 20.24,
                min: 16.58,
                max: 20.34,
                night: 16.58,
                eve: 17.11,
                morn: 17.49,
            },
            feels_like: {
                day: 20.07,
                night: 16.67,
                eve: 17.28,
                morn: 17.38,
            },
            pressure: 1000,
            humidity: 67,
            dew_point: 13.92,
            wind_speed: 8.44,
            wind_deg: 201,
            wind_gust: 16.55,
            weather: [
                {
                    id: 502,
                    main: 'Rain',
                    description: 'heavy intensity rain',
                    icon: '10d',
                },
            ],
            clouds: 99,
            pop: 1,
            rain: 19,
            uvi: 0.94,
        },
        {
            dt: 1695294000,
            sunrise: 1695275058,
            sunset: 1695319398,
            moonrise: 1695302160,
            moonset: 1695327540,
            moon_phase: 0.2,
            temp: {
                day: 17.82,
                min: 12.59,
                max: 17.83,
                night: 13.69,
                eve: 15.03,
                morn: 13.05,
            },
            feels_like: {
                day: 17.09,
                night: 13.18,
                eve: 14.44,
                morn: 12.76,
            },
            pressure: 995,
            humidity: 55,
            dew_point: 8.51,
            wind_speed: 5.29,
            wind_deg: 213,
            wind_gust: 12.64,
            weather: [
                {
                    id: 502,
                    main: 'Rain',
                    description: 'heavy intensity rain',
                    icon: '10d',
                },
            ],
            clouds: 39,
            pop: 1,
            rain: 9.15,
            uvi: 3.33,
        },
        {
            dt: 1695380400,
            sunrise: 1695361553,
            sunset: 1695405658,
            moonrise: 1695393000,
            moonset: 1695416760,
            moon_phase: 0.25,
            temp: {
                day: 13.31,
                min: 10.6,
                max: 15.09,
                night: 11.24,
                eve: 12.97,
                morn: 10.6,
            },
            feels_like: {
                day: 12.26,
                night: 10.04,
                eve: 11.76,
                morn: 9.86,
            },
            pressure: 1005,
            humidity: 60,
            dew_point: 5.74,
            wind_speed: 5.55,
            wind_deg: 289,
            wind_gust: 8.75,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: 89,
            pop: 0.21,
            uvi: 2.98,
        },
        {
            dt: 1695466800,
            sunrise: 1695448049,
            sunset: 1695491919,
            moonrise: 1695483060,
            moonset: 1695507060,
            moon_phase: 0.27,
            temp: {
                day: 16.78,
                min: 9.28,
                max: 17.14,
                night: 16.3,
                eve: 15.79,
                morn: 9.34,
            },
            feels_like: {
                day: 15.98,
                night: 15.68,
                eve: 15.07,
                morn: 8.32,
            },
            pressure: 1015,
            humidity: 56,
            dew_point: 7.92,
            wind_speed: 5.96,
            wind_deg: 216,
            wind_gust: 13.15,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            clouds: 87,
            pop: 0.39,
            rain: 0.12,
            uvi: 3,
        },
        {
            dt: 1695553200,
            sunrise: 1695534544,
            sunset: 1695578179,
            moonrise: 1695572160,
            moonset: 0,
            moon_phase: 0.31,
            temp: {
                day: 18.63,
                min: 16.4,
                max: 20.09,
                night: 17.45,
                eve: 19.62,
                morn: 16.53,
            },
            feels_like: {
                day: 18.74,
                night: 17.31,
                eve: 19.78,
                morn: 16.51,
            },
            pressure: 1016,
            humidity: 84,
            dew_point: 15.8,
            wind_speed: 6.67,
            wind_deg: 202,
            wind_gust: 13.56,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            clouds: 100,
            pop: 0.42,
            rain: 2.09,
            uvi: 3,
        },
        {
            dt: 1695639600,
            sunrise: 1695621040,
            sunset: 1695664440,
            moonrise: 1695660480,
            moonset: 1695598380,
            moon_phase: 0.35,
            temp: {
                day: 23.46,
                min: 17.16,
                max: 23.46,
                night: 19.24,
                eve: 20.47,
                morn: 17.94,
            },
            feels_like: {
                day: 23.43,
                night: 19.49,
                eve: 20.64,
                morn: 18.09,
            },
            pressure: 1023,
            humidity: 60,
            dew_point: 15.29,
            wind_speed: 4.96,
            wind_deg: 214,
            wind_gust: 11.43,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: 99,
            pop: 0.02,
            uvi: 3,
        },
    ],
};
